import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'agent-router',
    'layouts-guide',
    {
      type: 'category',
      label: '🟢 Ops & Incidents',
      collapsible: true,
      collapsed: false,
      items: [
        'templates/service-status',
        'templates/runbook-pipeline-failure',
        'templates/incident-postmortem-inc-2026-0031',
        'templates/meeting-2026-06-01',
        'templates/retro-sprint-4',
        'templates/team-directory',
      ],
    },
    {
      type: 'category',
      label: '🔒 Compliance & Governance',
      collapsible: true,
      collapsed: false,
      items: [
        'templates/change-request-cr-2026-0142',
        'templates/sdlc-gate-checklist-pipeline-v1-4',
        'templates/it-control-evidence-itgc-001',
      ],
    },
    {
      type: 'category',
      label: '🏛️ Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'templates/adr-001',
        'templates/rfc-002-async-messaging',
        'templates/tech-radar',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Engineering Maturity',
      collapsible: true,
      collapsed: false,
      items: [
        'templates/tech-debt-register',
        'templates/slo-pipeline-server',
        'templates/dora-metrics',
      ],
    },
    {
      type: 'category',
      label: '📊 Data Governance',
      collapsible: true,
      collapsed: false,
      items: [
        'templates/data-dictionary-pipeline',
        'templates/data-contract-pipeline-events',
        'templates/ml-model-card-content-classifier',
      ],
    },
    {
      type: 'category',
      label: '🚀 Onboarding & Knowledge',
      collapsible: true,
      collapsed: false,
      items: [
        'templates/onboarding-guide',
        'templates/glossary',
      ],
    },
    {
      type: 'category',
      label: '💻 Docs as Code',
      collapsible: true,
      collapsed: false,
      items: [
        'templates/code-walkthrough-pipeline',
        'templates/changelog-pipeline',
        'templates/env-reference-pipeline',
        'templates/architecture-diagram-pipeline',
        'templates/code-snippets-platform',
        'templates/attachment-demo',
      ],
    },
    {
      type: 'category',
      label: '📚 Tutorial',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
